
on:
    push:
        branches: [dev]
    pull_request:
        paths: ['.css', '.js', '.jsx']

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: npm install
              env:
                  CI: true

            - name: Run prettier
              run: npm run prettier --write 'src/**/*.{css,js,vue}'

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply prettier changes
