name: Continous Integration

on:
    pull_request:
        branches: [dev]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm test
            - run: npm run build
    prettier_format:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2
              - name: Install
                run: yarn install
                env:
                    CI: true
              - name: Run prettier
                run: yarn run prettier --write 'src/**/*.{css,js,jsx}'
              - uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Apply prettier changes
